config/routes.rb
Rails.application.routes.draw do
  resources :tournois do
    resources :wars
  end
  resource :geocoder

  resources :users
  resources :games
  resources :rankings

  root :to => "tournois#index"

  get 'delete_tournoi/(:id)', to: "tournois#destroy", :as => "delete_tournoi"
  get 'register_tournoi/(:id)', to: "tournois#register", :as => "register_tournoi"

  devise_for :users,:controllers => { registrations: 'registrations',:omniauth_callbacks => "callbacks" }, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  
  devise_scope :user do
    get "sign_in", to: "devise/sessions#new"
    get 'sign_out', :to => 'devise/sessions#destroy'
  end

end

app/models/tournoi.rb
class Tournoi < ActiveRecord::Base
	has_many :games, through: :tournoi_games
	has_many :tournoi_games
	has_many :users, through: :register_tournois 
	has_many :register_tournois
	has_many :wars
	has_one :location, :as => :locatable
  	accepts_nested_attributes_for :location
  	validates_presence_of :name,:date,:nbPlayerMax



  	def already_register?(user)
		self.register_tournois.where(user_id: user.id).any?
  	end
  	def full?
  		self.users.count < self.nbPlayerMax
  	end


  	#DEFINE
  	WIN = 3
  	LOOSE = 0
  	NULL = 1





end

app/controllers/tournois_controller.rb
class TournoisController < ApplicationController
  authorize_resource
  before_action :authenticate_user!
  before_action :acces_admin, only: [:edit,:show, :edit, :update, :destroy]
  before_action :set_tournoi, only: [:show, :edit, :update, :destroy, :register]

  #before_action :check_wars_blank, only: [:update, :edit]
  #respond_to :html

  def index
    if user_signed_in?
      @tournois = Tournoi.all
      @user = current_user
    else 
      redirect_to new_user_session_path
    end
  end

  def show
    set_tournoi
    @game = Game.all
  end

  def new
    @tournoi = Tournoi.new
    @games = Game.all
    1.times { @tournoi.build_location }
  end

  def edit
      @gamesNotUsed = @tournoi.wars.pluck(:game_id).uniq
      @gamesUsed = Game.where(id: @gamesNotUsed)
      @games = Game.where.not(id: @gamesNotUsed)
      authorize! :edit, @tournoi if can? :edit, @tournoi
  end

  def create
    @tournoi = Tournoi.new(tournoi_params)
    @war = @tournoi.wars
    @games = Game.all
    if @tournoi.save
      flash[:notice] = "Tournoi créé avec succès"
      redirect_to root_path
     else
      render :action => 'new'
    end
  end

  def update
    @games = Game.all
    if @tournoi.update_attributes(tournoi_params)
      redirect_to (@tournoi)
    end
  end

  def destroy
    @tournoi.tournoi_games.where("tournoi_id = ?",params[:id]).delete_all
    @tournoi.register_tournois.where("tournoi_id = ?",params[:id]).delete_all
    if @tournoi.destroy
      flash[:notice] = "Le tournoi a été supprimé avec succès"
      redirect_to root_path
    end
  end

  def register
    @register_tournoi = RegisterTournoi.new
    @register_tournoi.user_id = current_user.id
    @register_tournoi.tournoi_id = params[:id]
    if @tournoi.nbPlayerMax > @tournoi.users.count && @register_tournoi.save
        redirect_to root_path
    else 
       flash[:warning] = "Vous ne pouvez pas vous enregistrer ou réenregistrer à ce tournoi"
      redirect_to root_path
    end
  end

  private
    def set_tournoi
      @tournoi = Tournoi.find(params[:id])
    end

    def tournoi_params
      params.require(:tournoi).permit(:name, :place, :nbPlayerMax, :date, location_attributes: [:address], :game_ids => [])
    end

    def acces_admin
      current_user.admin?
    end
    def check_wars_blank
      unless @tournoi.wars.blank?
        flash[:notice] = "Ce tournoi a déjà des matchs en cours ou cloturés, il ne peut être édité."
        redirect_to tournoi_path
      end
    end
end

app/helpers/tournois_helper.rb
module TournoisHelper
end

app/views/tournois/_form.html.haml
= form_for(@tournoi) do |f|
  - if @tournoi.errors.any?
    #error_explanation
      %h2
        = pluralize(@tournoi.errors.count, "error")
        prohibited this tournoi from being saved:
      %ul
        - @tournoi.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :nbPlayerMax
    %br/
    = f.text_field :nbPlayerMax
  .field
    = f.label :date
    %br/
    = f.date_select :date
    %br/
    .field
      %br
      - @gamesUsed.each do |game|
        = game.title
        %br
      - @games.each do |game|
        = check_box_tag("tournoi[game_ids][]", game.id , @tournoi.game_ids.include?(game.id))
        = game.title
        %br
      = fields_for "tournoi[location_attributes]", @tournoi.location do |task_form|
        %br
        Adresse
        %br/
        = task_form.text_field :address

  .actions
    = f.submit

app/views/tournois/_ranking.html.haml
%table.table
	%thead
		%tr
			%th
				Nom du joueur
			%th
				Score total
	- @tournoi.users.each do |tu|
		%tbody
			%tr
				%td=tu.email
				%td=@tournoi.wars.where(user_1_id: tu.id).sum(:scorej1) + @tournoi.wars.where(user_2_id: tu.id).sum(:scorej2)

app/views/tournois/edit.html.haml
%h1 Editing tournoi

= render 'form'

= link_to 'Show', @tournoi 
|
= link_to 'Back', tournois_path 

app/views/tournois/index.html.haml
%h1 Liste des tournois
.row
  .col-md-2
    Nom
  .col-md-2
    Lieu
  .col-md-1
    Nombre de joueur max
  .col-md-1
    Nombre d'inscrits
  .col-md-1
    Date
  .col-md-2
    Distance (km)
  .col-md-1
- @tournois.each do |tournoi| 
  .row
    .col-md-2
      = tournoi.name 
    .col-md-2
      - if !tournoi.location.blank?
        = tournoi.location.address
    .col-md-1
      = tournoi.nbPlayerMax 
    .col-md-1
      = tournoi.users.count
    .col-md-2
      = tournoi.date
    .col-md-1 
      - if !current_user.location.blank? && !tournoi.location.blank?
        = current_user.location.distance_from([tournoi.location.latitude,tournoi.location.longitude]).round(2)
    .col-md-1
      %td= link_to 'Show', tournoi
      %br
      - if !tournoi.already_register?(current_user) && tournoi.full?
        %td= link_to "S'enregister", register_tournoi_path(tournoi)
        %br
      - if can? :update, @tournoi
        %td= link_to 'Edit', edit_tournoi_path(tournoi)
        %br 
      - if can? :destroy, @tournoi
        %td= link_to 'Destroy', delete_tournoi_path(tournoi), method: :delete, data: { confirm: 'Are you sure?' }
      %br
      
- if can? :create, @tournoi
  =link_to 'New Tournoi', new_tournoi_path 

app/views/tournois/new.html.erb
<h1>New tournoi</h1>

<%= render 'form' %>

<%= link_to 'Back', tournois_path %>

app/views/tournois/show.html.haml
%p
  %strong Name:
  = @tournoi.name
%p
  %strong Place:
  = @tournoi.place
%p
  %strong Nbplayermax
  = @tournoi.nbPlayerMax
%p
  %strong Date:
  = @tournoi.date
%p
  %strong Jeux sélectionnés:
  %br
  - @tournoi.games.each do |tg|
    %h5
      %span.label.label-default=tg.title
    = tg.description
    %br
    - @var = 1
    - wars = @tournoi.wars.where(game_id: tg.id)
    - if wars.blank?
      %br
      Il n'y a pas de match pour ce jeu
    - else
      .col-xs-12
        .col-xs-9
          %table.table
            %thead
              %tr
                %th
                  ==#
                %th
                  Joueur 1
                %th
                  
                %th 
                  Joueur 2
                %th 
                  Score J1
                %th 
                  Score J2
                %th     
            - wars.each do |tw|
              %tbody
                %tr
                  %td
                    Match 
                    = @var
                    - @var +=1
                  %td=User.find(tw.user_1_id).email 
                  %td 
                    VS 
                  %td=User.find(tw.user_2_id).email  
                  - if tw.scorej1.blank?
                    = form_for [@tournoi,@tournoi.wars.find(tw)], :remote => true do |f|
                      %td
                        = f.select(:scorej1, [['Win', Tournoi::WIN], ['Loose',Tournoi::LOOSE], ['Null', Tournoi::NULL]])
                      %td=f.submit
                  - else
                    %td= tw.scorej1
                    %td= tw.scorej2

      
%p
  %strong Utilisateurs enregistrés:
  %br
  - @tournoi.users.each do |tu|
    = tu.email
    %br  
%p
  %strong Score des users
  %br
  .col-xs-12
    .col-xs-5
      = render 'ranking'
- if can? :create, @war
  =link_to 'Play', new_tournoi_war_path(@tournoi)
- if can? :update, @tournoi
  = link_to 'Edit', edit_tournoi_path(@tournoi)
= link_to 'Back', tournois_path