config/routes.rb
Rails.application.routes.draw do
  resources :tournois do
    resources :wars
  end
  resource :geocoder

  resources :users
  resources :games
  resources :rankings

  root :to => "tournois#index"

  get 'delete_tournoi/(:id)', to: "tournois#destroy", :as => "delete_tournoi"
  get 'register_tournoi/(:id)', to: "tournois#register", :as => "register_tournoi"

  devise_for :users,:controllers => { registrations: 'registrations',:omniauth_callbacks => "callbacks" }, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  
  devise_scope :user do
    get "sign_in", to: "devise/sessions#new"
    get 'sign_out', :to => 'devise/sessions#destroy'
  end

end

app/models/game.rb
class Game < ActiveRecord::Base
	belongs_to :user
	has_many :tournois, through: :tournoi_games
	has_many :tournoi_games
	has_many :wars
	validates_uniqueness_of :title
	validates_presence_of :title,:description


	def users 
		user_ids = (self.wars.pluck(:user_1_id).uniq+self.wars.pluck(:user_2_id).uniq).uniq
		users = User.find(user_ids)
	end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	def new
		@game = Game.new
	end

	def create
		@game = current_user.games.new(game_params)
		if @game.save
      redirect_to (@game)
    else
      flash[:error] = "Le formulaire a été mal complété"
        render :action => :new
    end
	end

	def index
    	@game = Game.all
  end

  def edit
  	@game = Game.find(params[:id])
  end
  	
  def destroy
  	@game.destroy
  end
  	
  def update
    @game = current_user.games.find(params[:id])
  	if @game.update_attributes(game_update)
      redirect_to (@game)
    else
      flash[:error] = "Le formulaire a été mal complété"
        render :action => :edit
    end
  end

  def show 
    @game = Game.find(params[:id])
  end
  
	private

	def game_params
		params.require(:game).permit(:title, :description, :user_id)
	end
  def game_update
    params.require(:game).permit(:title, :description)
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.haml
= form_for @game do |f|
  .field
    = f.label :titre 
    %br
    = f.text_field :title
  .field
    = f.label :description 
    %br
    = f.text_area :description
  .actions
    = f.submit

app/views/games/edit.html.haml
%h1 Edition du jeu
= render 'form'
= link_to 'Back', games_path

app/views/games/index.html.haml
%h1 Liste des jeux
%table
  %thead
    %tr
      %th Titre
      %th Description
      %th Créateur
      %th{:colspan => "3"}
  %tbody
    - @game.each do |g| 
      %tr
        %td= g.title 
        %td= g.description
        %td= g.user.name
        - if current_user.admin?
          %td= link_to 'Edit', edit_game_path(g) 
          %br
= link_to 'Nouveau jeu', new_game_path 

app/views/games/new.html.haml
%h1 Nouveau jeu
= render 'form'
= link_to 'Back', tournois_path

app/views/games/show.html.haml
%p#notice= notice

%p
  %strong Titre:
  = @game.title
%p
  %strong Description:
  = @game.description
- if current_user.admin?
  = link_to 'Edit', edit_game_path(@game)  |
  = link_to 'Back', games_path