config/routes.rb
Rails.application.routes.draw do
  resources :tournois do
    resources :wars
  end
  resource :geocoder

  resources :users
  resources :games
  resources :rankings

  root :to => "tournois#index"

  get 'delete_tournoi/(:id)', to: "tournois#destroy", :as => "delete_tournoi"
  get 'register_tournoi/(:id)', to: "tournois#register", :as => "register_tournoi"

  devise_for :users,:controllers => { registrations: 'registrations',:omniauth_callbacks => "callbacks" }, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  
  devise_scope :user do
    get "sign_in", to: "devise/sessions#new"
    get 'sign_out', :to => 'devise/sessions#destroy'
  end

end

app/views/layouts/application.html.haml
%html
  %head
  %title RailsGame
  = stylesheet_link_tag "application", media: "all" 
  = javascript_include_tag "default"
  = csrf_meta_tag 
  %body
    - if user_signed_in?
      %nav.navbar.navbar-default
        .container-fluid
          / Brand and toggle get grouped for better mobile display
          .navbar-header
            %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            %a.navbar-brand{:href => "#"} Rails Game
          / Collect the nav links, forms, and other content for toggling
          #bs-example-navbar-collapse-1.collapse.navbar-collapse
            %ul.nav.navbar-nav
              %li= link_to ('Liste des tournois'), root_path
              %li=link_to ('Classement'), rankings_path
              %li=link_to ('Editer mon profil'),edit_user_path(current_user)
              %li=link_to ('Déconnexion'), sign_out_path
              - if current_user.admin?
                %li
                  Vous êtes un administrateur
                %li=link_to ('Ajouter un nouveau jeu'), new_game_path
                %li=link_to ('Liste des jeux'), games_path
              - else 
                %li
                  Vous êtes un utilisateur
    .container
      %p#notice= notice
      =flash[:warning]
      =flash[:error]
      =yield

     